# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.TextField(max_length=100)),
                ('team2', models.TextField(max_length=100)),
                ('win1', models.TextField(max_length=5)),
                ('win2', models.TextField(max_length=5)),
                ('draw', models.TextField(max_length=5)),
            ],
        ),
    ]
