# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='draw',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='win1',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='win2',
            field=models.TextField(max_length=15),
        ),
    ]
