# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161103_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='draw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='event',
            name='win1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='event',
            name='win2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
