# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161104_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.TextField(max_length=100)),
                ('win1', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('win2', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('draw', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('_1X', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('_X2', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
            ],
        ),
    ]
